name: Preview Docker Image on deploys.app

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  build:
    concurrency:
      group: preview-build-${{ github.ref }}
      cancel-in-progress: true
    name: Build and push Docker preview image
    runs-on: ubuntu-latest
    environment: Staging
    outputs:
      build-image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.6.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value={{sha}}-${{ github.actor }}
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        id: build
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  migrate:
    concurrency:
      group: preview-migrate-${{ github.ref }}
      cancel-in-progress: true
    name: Migrate database for preview
    needs: build
    runs-on: ubuntu-latest
    environment: Staging
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}\&schema=preview-${{ github.event.number }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}\&schema=preview-${{ github.event.number }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Migrate Prisma
        run: pnpm prisma migrate deploy

      - name: Seed Prisma
        run: pnpm prisma db seed

  deploy:
    concurrency:
      group: preview-deploy-${{ github.ref }}
      cancel-in-progress: true
    name: Deploy preview to deploys.app
    needs: [migrate, build]
    runs-on: ubuntu-latest
    environment: Staging
    env:
      DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
      DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Add Deploy Status to PR
        id: deploy-status
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.DEPLOY_TOKEN }}
          message: |
            ### <span aria-hidden="true">🚀</span> Preview deployment is in progress...

            The preview deployment is being prepared. This may take a few minutes. Please wait for the deployment to complete before checking the preview URL.
            | Name | Resource |
            |:-:|------------------------|
            |<span aria-hidden="true">🔨</span> Latest Commit | ${{ github.sha }} |
            |<span aria-hidden="true">📦</span> Image Digest | ${{ needs.build.outputs.build-image-digest }} |

      # I know there is a proper action for this, but it doesn't provide a way to configure ENV
      - name: Call Deploys.app Deploy API
        id: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.deploys.app/deployment.deploy'
          method: 'POST'
          timeout: 15000
          username: ${{ secrets.DEPLOYS_AUTH_USER }}
          password: ${{ secrets.DEPLOYS_AUTH_PASS }}
          contentType: 'application/json'
          data: |
            {
              "location": "gke.cluster-rcf2",
              "project": "buddyrental-api",
              "name": "preview-${{ github.event.number }}",
              "image": "ghcr.io/${{ github.repository }}@${{ needs.build.outputs.build-image-digest }}",
              "env": {
                "DATABASE_URL": "${{ secrets.DATABASE_URL }}&schema=preview-${{ github.event.number }}",
                "DIRECT_URL": "${{ secrets.DIRECT_URL }}&schema=preview-${{ github.event.number }}",
                "NODE_ENV": "preview"
              },
              "resources": {
                "limits": { "cpu": "1" },
                "requests": { "memory": "0" }
              }
            }

      - name: Install Deploys CLI
        run: scripts/install-deploys-cli.sh

      - name: Create Route on Deploys.app
        run: |
          deploys route create \
            -project=buddyrental-api \
            -location=gke.cluster-rcf2 \
            -domain=buddyrental-preview-${{ github.event.number }}.tonklaw.com \
            -deployment=preview-${{ github.event.number }}

      - name: Update Deploy Status to PR
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.DEPLOY_TOKEN }}
          message: |
            ### <span aria-hidden="true">🚀</span> Preview deployment is ready!

            The preview deployment is ready. You can access the preview at [buddyrental-preview-${{ github.event.number }}.tonklaw.com](https://buddyrental-preview-${{ github.event.number }}.tonklaw.com).

            | Name | Resource |
            |:-:|------------------------|
            |<span aria-hidden="true">🔨</span> Latest Commit | ${{ github.sha }} |
            |<span aria-hidden="true">📦</span> Image Digest | ${{ needs.build.outputs.build-image-digest }} |
